### PR TITLE
fixes var name $ds -> $remap

### LINKED ISSUE #3498: TO compilation error - Bareword "RRH_CACHE_RANGE_REQUEST" not allowed while "strict subs"
Reported by @dangogh 

```
[2019-04-17 19:54:22,069] [ERROR] Bareword "RRH_CACHE_RANGE_REQUEST" not allowed while "strict subs" in use at /opt/traffic_ops/app/lib/UI/DeliveryService.pm line 1440.
```

```
BEGIN failed--compilation aborted at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 24.
```

Introduced by #3444

### PR DESCRIPTION
**Pull request by dangogh**
## What does this PR (Pull Request) do?

- [x] This PR fixes #3498 for an incorrect variable reference introduced in #3452 

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?

start cdn-in-a-box:
```
cd infrastructure/cdn-in-a-box
cp ../../dist/traffic_ops*x86.rpm ./traffic_ops/traffic_ops.rpm
docker-compose up --build -d
docker-compose logs -f trafficops-perl
```

Examine the output for this message: 
 ```[ERROR] Global symbol "$ds" requires explicit package name at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 2896.```

Simple var reference fix -- no docs, tests, changelog changes needed.

## If this is a bug fix, what versions of Traffic Ops are affected?
- master (21e50ee)

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3543/
Test PASSed.
