### ISSUE TITLE
TO compilation error - Bareword "RRH_CACHE_RANGE_REQUEST" not allowed while "strict subs"

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#3498]
Reported by @dangogh 

```
[2019-04-17 19:54:22,069] [ERROR] Bareword "RRH_CACHE_RANGE_REQUEST" not allowed while "strict subs" in use at /opt/traffic_ops/app/lib/UI/DeliveryService.pm line 1440.
```

```
BEGIN failed--compilation aborted at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 24.
```

Introduced by #3444

**Comment by rawlinp** [comment]
I believe I already fixed this issue in https://github.com/apache/trafficcontrol/pull/3490 a couple days ago.

**Comment by dangogh** [comment]
I'll build a new rpm and try out again..

**Comment by dangogh** [comment]
fixed in #3490 ,  but another issue cropped up in the same file:
```trafficops-perl_1  | [2019-04-17 21:29:01,436] [ERROR] Global symbol "$ds" requires explicit package name at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 2896.```
